<!-- Short abstract for MGRO/Bridges: -->
<!-- currently 117 words, may need to be cut to 100 -->
<!--
As the dimensionality of data increases, so does the difficulty in their visualization. Traditional linear projections view discrete pairs of linear components. _Tours_ are a class of linear projections that animate over small changes to the projection. The _manual tour_ uniquely enables an analyst to steer a path of bases. This thesis discusses an __R__ package that facilitates their creation. A user study finds the manual tour outperforms traditional visualizations on a variable attribution task. Local explanations increase the interpretability of nonlinear models by approximating the variable importance at the vicinity of one observation. This work introduces a novel approach to explore the support of explanations with the radial tour. An accompanying package facilitates this analysis.
-->

# Abstract {-}

<!-- EDA, motivation, linear projections, tours -->
Visualizing data space is a crucial aspect of exploratory data analysis, checking assumptions, and validating model performance. However, visualization quickly becomes complex as the dimensionality of the data or features increases. Traditionally, linear projections have viewed discrete pairs of components to mitigate this complexity. Data visualization _tours_ are a class of dynamic linear projections that animate many linear projections over small changes to the projection basis. The permanence of observations between nearby frames potentially conveys more information than discrete orthogonal frames alone.

<!-- manual tours and spinifex -->
Tours are categorized by the path of their bases. _Manual tours_ uniquely allow for user-controlled steering of a path of bases, where the contributions of individual variables can be changed. The _radial tour_ is a specific case of the manual tour, that freezes the angle of movement but allows the magnitude to be varied. This is used in the work reported here. Chapter \@ref(ch-spinifex) defines and clarifies the theoretical basis of the radial tour. The details of implementation and illustration of its use are provided. It introduces an open-source __R__ package, that facilitates creating these tours with a variety of display choices and user controls. <!--An interactive application, vignettes, and example code illustrate the use of the radial tour.-->

<!-- user study -->
Allowing the analyst to steer a path in the radial tour should enable a better understanding of the variable importance to any structure revealed in a projection. Chapter \@ref(ch-userstudy) discusses a within-participant user study comparing the radial tour with current practices: principal component analysis (PCA) and the original type of tour that has no steering. The $n=108$ crowdsourced participants performed a variable attribution task describing the separation between clusters. The results find that the radial tour lead to more accurate variable attribution. Participants also reported that the radial tour was their preferred visualization method.

<!-- cheem -->
Nonlinear modeling techniques are sometimes referred to as black-box models due to the uninterpretable nature of model terms. Recent research in Explainable Artificial Intelligence (XAI) tries to bring these models interpretability through _local explanations_. Local explanations are a class of techniques that approximate the linear-variable importance for prediction at one point in the data. Chapter \@ref(ch-cheem) provides a new approach for exploring the variable sensitivity of local explanations using radial tour. Local explanations can be considered projection bases. The radial tour is used to vary the contribution of an feature to assess the importance that feature for any particular prediction. This is illustrated using four contemporary data examples covering classification and regression. An accompanying __R__ package provides a graphical user interface (GUI) for conducting this analysis.

<!-- The following line is required to re-set page numbering after preliminary material. Do not remove -->
\clearpage\pagenumbering{arabic}\setcounter{page}{0}
