`r if (knitr::is_html_output()) '<!--'` 

# Declaration {-}

I hereby declare that this thesis contains no material which has been accepted for the award of any other degree or diploma at any university or equivalent institution and that, to the best of my knowledge and belief, this thesis contains no material previously published or written by another person, except where due reference is made in the text of the thesis.


## Publication as part of this thesis {-}

The work corresponding to Chapter \@ref(ch-spinifex) has been accepted for publication in _The R Journal_ [@spyrison_spinifex_2020]. While respective studies discussed in Chapters \@ref(ch-userstudy) and \@ref(ch-cheem) have not yet been submitted.
<!-- <<KM strikethrough, 20 Jan>>This paper clarifies some of the theoretical work for user control offered by the manual tour and induces an open-source __R__ package facilitating manual tours. The user study described in Chapter \@ref(ch-userstudy) compares the performance of three linear projections and will shortly be submitted to the _IEEE Transactions on Visualization and Computer Graphics_. This study finds large evidence for a sizable increase in a variable attribution task from the user control of the manual tour over principal component analysis and the grand tour. Then we extend the interpretability of complex non-linear models. I purpose exploring the support of local explanation of a model with the manual tour. This research covered in Chapter \@ref(ch-cheem) will shortly be submitted to _The Journal of Machine Learning research_. -->

I have renumbered and updated sections of the published paper to generate a consistent presentation within the thesis. The code illustrated has been adjusted to highlight the new ggproto API. Introductory, background, and conclusion content has been moved to their respective thesis chapters.
 

## Publications and papers during candidature not part of this thesis {-}

In addition to the research discussed in the thesis, other notable contributions during my candidature include:

- _The state-of-the-art on tours for dynamic visualization of high-dimensional data_ [@lee_state_2021]. A WIREs Computational Statistics Review of current tour methods. I contributed writing and visuals  discussing manual tours.
- _"Is IEEE VIS that good?" On key factors in the initial assessment of manuscript and venue quality_ [@spyrison_is_2021]. A survey IEEE VIS authors, how they source articles, decide which to read, and evaluate venue quality. We find low evidence that sentiment changes across academic positions for these topics and provide commentary and discussion on the effects of "publish or perish" environment, standard author and journal metrics, and the need to publish "null" findings and replication studies.
- _Intraday effect of COVID-19 restrictions on Melbourne electricity consumption_ [@barrow_changes_2020]. We corroborate that the Victorian interday effect on energy consumption did not change and novelly find that the intraday distribution of energy consumption does change. Namely, we find a statistically significant change in the height of the morning and evening peak, energy consumption that we posit is due to less strict schedules associated with working from home, absence of commute time, and other employment changes. We were awarded 1st place of hundreds of entries in the insights category of the Melbourne 2020 Datathon.
<!-- - Student volunteering at three conferences: UseR!2021 - Online, CHI Down Under 2020 - Online, and UseR!2018 - Brisbane, Australia. -->


\textbf{Student name:} Nicholas Spyrison

\textbf{Student signature:}

```{r, out.width = "33%", fig.align = "left"}
nsSafeIncGraphic("./figures/ch0_signature.PNG")
```

\textbf{Date:} `r as.Date("2021-12-12")`

`r if (knitr::is_html_output()) '-->'`

<!-- TRADITIONAL THESIS (NOT BY RESEARCH) DOES NOT INCLUDE THE BELOW IN DECLARATION -->
<!-- \vspace{2em} -->
<!-- \noindent -->
<!-- The undersigned hereby certify that the above declaration correctly reflects the nature and extent of the student's co-authors' contribution to this work. -->

<!-- \textbf{Main Supervisor name:} Kimbal Marriott -->

<!-- \textbf{Main Supervisor signature:} -->

<!-- \vspace*{2cm} -->

<!-- \textbf{Date:} `r as.Date("2021-12-12")` -->


<!--
All of the papers in the thesis were conceptualized, developed, and written by myself, the student, while working in the Department of Human-Centered Computing under the supervision of Professor Kimbal Marriott and Professor Dianne Cook. When co-authors are listed, it indicates that the work was produced through active collaboration between researchers and that their contributions to team-based research have been recognized. The following table details the work, including my and my fellow co-authors' contributions.

\begin{table}
\centering\footnotesize\tabcolsep=0.12cm
\begin{tabular}{|p{1cm}|p{2cm}|p{1.5cm}|p{3.5cm}|p{3.5cm}|p{1.5cm}|}
\hline
\RaggedRight\textbf{Thesis Chapter}  &
\RaggedRight\textbf{Publication Title}  &
\RaggedRight\textbf{Status (published, in press, accepted or returned for revision)}  & \RaggedRight\textbf{Nature and} {\%} \RaggedRight\textbf{of student contribution} & \RaggedRight\textbf{Co-author name(s) Nature and} {\%} \RaggedRight\textbf{of Co-author’s contribution} &
\RaggedRight\textbf{Co-author(s), Monash student Y/N} \\ \hline
3 & spinifex: an R package for creating
user-controlled animated linear projections & 75\%. Concept, development, writing first draft and software development & (1) Dianne Cook, concept, methodology, writing 25\% & N \\ \hline
4 & The benefit of user-controlled radial tour for understanding variable contributions to structure in linear projections & To be submitted & 80\%. Concept, development, writing first draft, application, and conducting user study & (1) Dianne Cook, Concept, methodology, editing 12\% (2) Kimbal Marriott, concept, methodology, editing 8\% & N \\ \hline
5 & Interrogating the linear variable importance of local explanations of non-linear models with animated linear projections & To be submitted & 85\%. Concept, development, writing first draft and software development & (1) Dianne Cook, methodology, editing 10\% (2) Kimbal Marriott, methodology, editing 5\% & N \\ \hline
\end{tabular}
\end{table}
-->
