# Acknowledgments {-}

<!-- Supervisors -->
I would like to express my sincere gratitude to my supervisors, Professor Dianne Cook and Professor Kimbal Marriott, for their support of my Ph.D studies and research, their subject expertise, and their careers supervising and teaching. Thank you for continuously pushing me and my research to new levels. I have enjoyed teaching data visualization, which has been strongly shaped by Di's practical, data-first, visualization-often approach. I will continue to hear Kim’s persistent question, “what do we learn from this?” as a reminder not to get lost in the implementation details and regularly step back and analyze if this is the correct object to change. Thanks to the member of supervisory panel, Associate Professor Bernhard Jenny, Dr. Maxime Cordeil, and Dr. Shirui Pan for their time, engagement, and suggestions throughout this research.

<!-- PhD students, promodo, Ying -->
Special thanks to Jieyang Chong and Julie Holden for their proofreading and suggested language clarifications. I thank my fellow Ph.D students, NUMBAT and DVIA lab members, and Pomodoro partners, primarily on the occasion of stimulating discussions and the positive peer pressure of knowing others are around and working. Thanks immensely to those who empathized with me and others, primarily through the hardships of studies and COVID-19. Gratitude to Ying Zhou for her enduring support through the thick of my studies and wavering mental health. 

<!-- Family -->
Last but not least, I would like to thank my parents, Doug and Terry, for their continued support and for airing my grievances at odd hours of the day. Thanks to Alan and Claire for their companionship and support now and in our more formative years.

<!-- Scholarship required shoutout -->
This research was supported in part by an Australian Government Research Training Program (RTP) Scholarship.