---
chapter: 6
knit: "bookdown::render_book"
---

# Conclusion {#ch-conclusion}

<!-- Context -->
We know that visualizing data is more robust than numerical summarization alone. It provides a means to rapidly get a feel for the data, check for erroneous values, and confirm model assumptions. But visualizing data spaces becomes increasingly complex as dimensionality increases. Linear dimension reduction and especially dynamic animations of linear projections, tours, seems to be a fruitful way to extend data visualization as dimensionality increases. Previously we haven't had a means of testing the sensitivity of individual variables' contribution to the structure in one embedding. In Chapter \@ref(ch-spinifex) introduced the __spinifex__ package, which facilitates user-controlled manual tours and extends the exporting of any tour, interoperability with __tourr__. Use of the radial, manual tour does sizably improve the accuracy on variable-level supervised cluster separation task compared with PCA and the grand tour. Chapter \@ref(ch-efficacy_radial_tour) covers the with-in participants user study that led to this conclusion. Finally, we extended the use of the manual tour to increase the interpretability of non-linear models by using it to explore their local explanations in the package __cheem__ is discussed in \@ref(ch-cheem).

<!-- user study -->
<!-- Chapter \ref{ch-efficacy_radial_tour} discussed a user study comparing the radial tour against PCA and the grand tour. Participants performed a variable attribution task of the supervised cluster separation. We define an accuracy measure for this task and the additional experimental factors location, shape, and dimensionality. I find strong evidence that use of the radial tour leads to high accuracy for this task. Using mixed model regression, I partition the error term of the model into the variation from participant's skill, and variation in difficult of the simulations due to random draws. -->


## Software development

<!-- spinifex -->
The __spinifex__ package facilitates the preprocess transformations with `scale_*` functions, identifies features with `basis_*` functions, and allows user-control over variable contributions to the basis with manual tours. It creates a framework for layered creation of tour visuals with `proto_*` functions will feel at home to __ggplot2__ users. Manual tours and those created from __tourr__ can be rendered and exported as interactive HTML widgets, .gif, or .mp4 files. Vignettes and interactive an application help users get started. It has been downloaded over 14,400 times from CRAN between 09 April 2019 and 28 November 2021. The package is available on [CRAN](https://CRAN.R-project.org/package=spinifex) with vignettes and version notes on its [pkgdown](https://nspyrison.github.io/spinifex/) site. My contributions __spinifex__ and __tourr__ won the ACEMS Impact and Engagement Award, 2018.

<!-- cheem -->
In the __cheem__ package, I suggest using manual tours to extend the interpretability of black-box models by exploring their local explanations. A workflow is developed to facilitate the creation of a random forest model, calculating tree SHAP local explanations for each observation. An interactive application illustrates the purposed visual and analysis from several datasets or upload your data after processing. Local explanations are evaluated through testing the sensitivity of the variables to the structure identified in the explanation. __cheem__ was recently uploaded to [CRAN](https://CRAN.R-project.org/package=cheem) and has a corresponding [pkgdown site](https://nspyrison.github.io/cheem/).


## Further extensions

<!-- General tour extension -->
In addition to controlling the contribution of a single variable, it may be insightful to able to change contributions of several at once (manipulating on a linear combination). A sort of dimension reduction tour that would append several manual tours together, zeroing the contributions of variables one at a time may prove interesting in the vicinity of the a features intrinsic dimensionality.

<!-- spinifex --> 
There are direct natural extensions to __spinifex__, such as extending the type of protos available, such as adding a text table of the basis, convex hulls, alpha hulls, and a 'high density region' display where the bulk of the data is shown as density contour, while the outer most observations are displayed as points [@hyndman_computing_1996]. An additional interpolation of the manual tour could correlate the frame number with the magnitude of a radial tour; the first frame would contain zero magnitude, and the last contains a full contribution, while the default starting frame would  initial value.

<!-- 2.5d & XR -->
Experiencing tours as 3D scatterplots in extended reality with stereoscopically true head tracking may be fruitful. [@nelson_xgobi_1998] explore 2D tour is in virtual reality. Other works view 3D scatterplot tours on 2D displays [@yang_3d_1999; @yang_interactive_2000]. It would be interesting to see modern implementations using WebGL, Mozilla A-frame, or Unity. One concern would be trying to keep hardware and software as generalized as possible.

<!-- cheem -->
Similarly, __cheem__ analysis could be generalized to a broader range models and local explanations. The models and local explanations facilitated by `DALEX::explain()` seems to be a good starting point [@biecek_dalex_2018; @biecek_explanatory_2021]. Alternatively, there may be other statistics that better show the structure identified by explanations that could be added.

<!-- tour apps --> 
<!-- In addition to application that involve one tour variant such as the applications we have discussed or __liminal__ [@lee_casting_2020], a general more consolidated application with multiple linked brushing would be nice to have. There have been many takes on applications to facilitate the exploration of multivariate data and the audience that know of and uses tours remains small. Tour-based applications [@fisherkeller_prim-9:_1974; @swayne_xgobi:_1991; @hardle_xplore:_1995; @carr_explorn:_1996; @nelson_xgobi_1998; @sutherland_orca:_2000; @swayne_ggobi:_2003] and other multi-variate data visualization applications [@carr_explor4:_1988; @tierney_lisp-stat:_1990; @huh_davis:_2002; @wegman_visual_2003; @jeong_ipca:_2009, hadjar_webvr_2018; cordeil_iatk_2019]. -->


## Other contributions

In addition to the research discussed around the thesis of the manual and radial, manual tour other notable contributions during my candidature include:

- _The state-of-the-art on tours for dynamic visualization of high-dimensional data_ [@lee_state_2021], WIREs Computational Statistics. Review of current tour methods. I contributed writing and manual tour frame discussing manual tours.
- _"Is IEEE VIS that good?" On key factors in the initial assessment of manuscript and venue quality_ [@spyrison_is_2021]. A survey IEEE VIS authors, how they source articles, decide which to read, and evaluate venue quality. We find low evidence that sentiment changes across academic positions for these topics and provide commentary and discussion on the effects of "publish or perish" environment, standard author and journal metrics, and the need to publish "null" findings and replication studies.
- _Intraday effect of COVID-19 restrictions on Melbourne electricity consumption_ [@barrow_changes_2020]. We corroborate that the Victorian interday effect on energy consumption did not change, and novelly find that the intraday distribution of energy consumption does change. Namely, we find a statistically significant change in the height of the morning and evening peak, energy consumption that we posit is due to less strict schedules associated with working from home, absence of commute time, and other employment changes. We were awarded 1st place of hundreds of entries in the insights category of the Melbourne 2020 Datathon.
- Student volunteering at three conferences: UseR!2021 - Online, CHI Down Under 2020 - Online, and UseR!2018 - Brisbane, Australia.
