---
chapter: 6
knit: "bookdown::render_book"
---

# Conclusion {#ch-conclusion}

<!-- Summary of work and importance -->
Most data are multivariate. This thesis makes important contributions to the interactive visualization of quantitative multivariate data. Data visualization can convey complexities in data such as heteroskedasticity and irregular shapes of distributions better than numerical summaries. Thus it is an essential activity for exploring data. However, it becomes more challenging when there are more than two variables (dimensions). It is common to tackle high-dimensions by reducing the dimensionality, and visualizing the lower dimensional data. This thesis provides a new methodology using linear dimension reduction, built on dynamic animation of linear projections, with a specific approach called a radial tour. This has benefits over traditional approaches that use only a small handful of low-dimensional views, because many low-dimensional projections are shown. In particular, the radial tour is designed to help the user understand the relationship between a single variable and structure visible in the projections.

The Introduction lists the over-arching question: _Can the radial tour, with user-steering of the basis, help analysts' understanding of the variable sensitivity to structure in the projection?_ This is divided into three research questions that were correspondingly addressed in the three content chapters. Chapter \@ref(ch-spinifex) developed a package addressing RQ 1 (How do we define and implement a user interface and interactions for the radial tours to add and remove variables smoothly from 1- and 2D linear data projections?). Chapter \@ref(ch-userstudy) discussed a user study to answer RQ 2; does the use of the interactive radial tour improve analysts' understanding of the relationship between variables and structure in 2D linear projections compared to existing approaches? Chapter \@ref(ch-cheem) covers the novel analysis and corresponding package responding to RQ 3, can the radial tours be used in conjunction with local explanations to improve the interpretability of black-box models?


## Contributions

The contributions of this thesis can be split into scientific knowledge and software development.


### Scientific knowledge

<!-- spinifex -->
Chapter \@ref(ch-spinifex) clarifies the radial tour methodology, specifically using Rodrigues' rotation formula [@rodrigues_lois_1840] to solve the rotation matrix defined for 1- and 2D tours. This use of the rotation formula sets up a scaffolding to extend the manual tour to three dimensions with another rotation angle to span the manipulation space. This work also supports radial tours by illustrating use cases on high-energy physics data sets.

<!-- user study -->
Chapter \@ref(ch-userstudy) discusses a user study to evaluate the efficacy of the radial tour as compared with PCA and the grand tour. It defines a task and accuracy measure for a variable attribution of the separation of two clusters. The $n=108$ crowdsourced user study compares the performance of these visuals across three experimental factors of simulated data. Mixed model regression finds considerable evidence for a sizable improvement in accuracy from the radial tour, which participants also subjectively prefer.

<!-- cheem -->
Chapter \@ref(ch-cheem) introduces cheem analysis. This extends the interpretability of nonlinear models by exploring local explanations with the radial tour. The global view gives a full observation summary of data space, attribution space, and residual plot side-by-side as a coordinated view. From this, an analyst identifies a primary observation to explore its explanation in detail and optionally compares it against another observation. The primary observation's normalized attribution becomes the starting basis for a radial tour. By varying the contributions of variables, an analyst tests the contribution's sensitivity to the predictive power identified in the explanation. We provide usage and discussion from four contemporary datasets.


### Software

<!-- spinifex -->
The __R__ package __spinifex__ facilitates the creation of manual tours, which allow an analyst to steer the contributions of a variable. <!---It handles data transformations and the identification of various starting bases.--> It creates a framework for the layered display of tours interoperable with the __tourr__ package. This extension of the geometric display of tours will feel at home to __ggplot2__ users. After composition, tours can be animated and exported as interactive or fixed animations. Vignettes and an interactive application help users rapidly understand the concepts facilitated by this work. The impact of __spinifex__ can be seen in two ways. My contributions to __spinifex__ and __tourr__ won the ACEMS Impact and Engagement Award, 2018. Furthermore, the package is available on [CRAN](https://CRAN.R-project.org/package=spinifex) with vignettes and version notes on its [pkgdown](https://nspyrison.github.io/spinifex/) site. It has been downloaded over 15,800 times from CRAN between 09 April 2019 and 27 February 2022.

```{r, eval=FALSE,echo=FALSE}
if(FALSE){
  ## takes a bit:
  spinifex_dl <- cranlogs::cran_downloads(
    packages = "spinifex", from = "2019-04-09", to = "2022-02-27")
  sum(spinifex_dl$count)
  ## [1] 15824 downloads
}
```

<!-- cheem -->
Given a compatible model, the __cheem__ package calculated the tree SHAP local explanations with __treeshap__. Functions perform the preprocessing to calculate the local explanations of all observations with several statistics that help describe the separability of data and attribution space. This processed object is then used to produce two novel visuals that are composed using  __spinifex__ and __ggplot2__ before being rendered with interaction with __plotly__. An interactive graphical user interface is made with __shiny__, using these visuals to facilitate the outlined cheem analysis. Several preprocessed datasets are included and allow analysts to upload their data after processing. This package was recently published at [CRAN](https://CRAN.R-project.org/package=cheem) and has a corresponding [pkgdown site](https://nspyrison.github.io/cheem/).


## Limitations

Below, we discuss several limitations with this work in chapter order. The following section echos this order and discusses possible directions to address these limitations.

<!-- 1_Manual tours in 1- & 2D -->
Manual tours (and radial tours) are limited in several ways. For instance, the work currently lists rotation matrices for 1- and 2D manual tours.<!-- 2_only 1var at a time--> Another limitation is that they only change one variable at a time. This can be cumbersome and timely if many variables need to be zeroed or otherwise modified.<!-- 3_Ink tank display --> The radial tour moves in three segments (total contribution, no contribution, initial contribution). It may be more approachable to directly relate the fraction of the slider to the magnitude of the variable's contribution.
<!-- >> 4_Pedagogical side of manual tours for newcomers; not on limitation side, mention more on the future work side. -->

<!-- 5_d>2 tour composition --> 
Setting aside the manual tour, there are several extensions to the layered composition of tours in __spinifex__, such as extending the geometric display type. Because the manual tour is currently defined for $d \in [1,2]$ projections, the geometric display for $d>2$ __tourr__-made tours are under-supported.<!-- 6_d=2 proto extensions, 7_Sterescopic 3D & XR --> Most tour implementations are made with 2D monitors in mind. It would be nice to have implementations for extended reality with a stereoscopic head-mounted display.

<!-- 8_User study -->
The user study evaluating the radial tour has several intrinsic limitations from the choice of visuals and levels of the experimental factors. It only considered discrete 2D PCA, grand tour, and manual tour for supervised cluster separation on mostly linear clusters in four and six dimensions. Trials we collected online due to the ongoing COVID-19 pandemic, which limited the audience and complexity of the task. 

<!--9_cheem, and model/explanation types-->
The cheem analysis was illustrated using the tree SHAP explanations on random forest models. The __cheem__ package handles several other tree-based models, though the analysis should be generalized to a broader base of models and compatible explanations.<!--10_data:quantitative matrices--> We also focus on quantitative matrices. This could be generalized to accommodate text, image, or time-series data.<!--11_Extending explanations and a user study-->
There is also no comparison evaluating the value of cheem analysis. It would be interesting to measure the benefit of cheem over local explanations or other observation-level evaluations of a model. 


## Future work

This section purposes possible directions to address or extend from the limitations outlined above.

<!-- 1_3D manual tour -->
Chapter \@ref(ch-spinifex) included the scaffolding to extend manual tours beyond 2D. Namely, this would require the use Rodrigues' rotation formula [@rodrigues_lois_1840] to define another rotation angle. The 3D projection would initialize a 4D manipulation space and use three input angles to control the contribution in the first three components. Another display dimension may benefit the detection and understanding of the higher dimensional structure, while we would also expect longer interaction time and less intuitive input.

<!-- 2_Manipulating multiple variables -->
In addition to the manual tour controlling the contribution of a single variable, it may be insightful to change the contributions of several variables at once (effectively manipulating a linear combination of variables). Varying combinations of variables may increase manipulation speed or prove to be unintuitive to input. Alternatively, an automated approach may help clean up variables with small contributions. A sort of dimension "reduction tour", could append several manual tours that sequentially zero the contributions of variables contributing less than some threshold, which may prove to expedite analysis, especially for approaching a feature's intrinsic dimensionality. This approach may be better as an initialization step before render time. This would abstract away some of the business and monotony of dealing with many variables allowing an analyst to focus on the variables that tangibly impact the projection.

<!-- 3_Ink tank display -->
Currently, the radial tour creates three segments (increase-decrease-increase of magnitude). An "ink tank" display for a manual tour may be more intuitive than the current approach. For this, the extent of contribution would match the progress of an animation slider. The first frame would contain zero variable contribution, and the last would have a total contribution. The starting frame could be the original contribution that would also be exaggerated or annotated for reference and navigation.

<!-- 4_Pedagogical side of manual tours for newcomers. -->
This last point is adjacent to the pedagogical side of tours and linear projections more broadly. The user-steering of the manual tour provides a way to play with projections and test hypotheses making it a good candidate as a learning tool. An interactive application built for teaching and exploring projection techniques would be a boon to scholars.

<!-- 5_geom/protos for d>2 -->
Extending the output dimensions of some tours is relatively easy to do. The display in __spinifex__  has focused on $d \in [1, 2]$. Additional functions could be added to facilitate non-axes based displays such as parallel coordinates, Chernoff faces, glyph-based, or pixel-based visuals. For the reasons mentioned in Chapter \@ref(ch-background), these displays are potentially best used with data with relatively few observations and many variables.

<!-- 6_2D tour composition --> 
There are also several extensions to the display of 1 & 2D tours, including tabular displaying the numeric values of the basis, drawing of lines around convex and alpha hulls, and a _high-density region_ displays with progressive density rugs, or a combination of point and density contour display where the bulk of the data is shown as density contour, while the outermost observations are displayed as points [@hyndman_computing_1996; @ohara-wild_gghdr_2022].

<!-- 7_Sterescopic 3D & XR -->
It may be interesting to experience tours as 3D scatterplots in extended reality with stereoscopically accurate head-tracking may be fruitful. @nelson_xgobi_1999 explore 2D tours in virtual reality. Other works view 3D scatterplot tours on 2D displays [@yang_3d_1999; @yang_interactive_2000]. It would be interesting to see modern implementations using WebGL, Mozilla A-frame, or Unity. One concern would be keeping hardware and software as generalized as possible.

<!-- 8_User study -->
There are some ways that the user-study evaluating the radial tour could be extended. The data could be changed to involve nonlinear shapes, outliers, or varying density and dimensionality. Besides changing the support of the experimental factors to the user study, it may be more interesting to evaluate across different tasks or compare other visualization techniques --- scatterplot matrices, parallel coordinate plots, or ridge plots of principal component approximations may be realistic. The performed user study crowdsourced participants with little exposure to linear projections. It would be interesting to compare the results from more experienced participants.

<!-- 9_cheem, and model/explanation types -->
The outlined cheem analysis can be generally applied models and local explanations. While the package __cheem__ currently calculates tree SHAP for tree-based models supported by __treeshap__ [@kominsarczyk_treeshap_2021]. This could be generalized more broadly to other models and local explanations. Those facilitated by `DALEX::explain()` seem to be an excellent direction to extend [@biecek_dalex_2018; @biecek_explanatory_2021]. However, processing runtime is a looming obstacle that is exasperated when moving away from computationally efficient explanations. Alternatively, other statistics may better show the structure identified in the attribution space from the explanations.

<!-- 10_cheem, scope/context of data -->
In the cheem analysis, we had focused primarily on continuous quantitative predictors. Perhaps this analysis could be extended to image, text, or time series analysis. The global view may remain helpful in summary and identification while observation-level exploration would likely need to change to fit the context of the data, be it saliency map, word-level contextual sentiment analysis, or other. <!--The presence of covariates in these cases may prove essential to having meaningful variable importance to test variable sensitivity of the structure of the explanation. -->

<!-- 11_cheem user study -->
A user study would help elucidate the benefit of cheem analysis over local explanations or observation-specific analysis of a model. Our analysis can highlight the unique attribution of a selected observation against peers and test the sensitivity of that attribution. Perhaps a task identifying variable sensitivity to a prediction may be appropriate.


<!-- XXX TODO: more grep searches for broken stuff '??', '-cap', 'ref' -->
<!-- XXX TODO: more astrogrep 'paper', convert to chapter or equiv -->
<!-- XXX TODO: Does CRAN cheem url exist; https://CRAN.R-project.org/package=cheem  ? -->


