# Overall appendix

<!-- !!!LATEX TABLES WILL NOT WORK IN HTML, need to use kbl... -->
```{r}
glossary_df <- data.frame(
  Term = c("observation", "variable", "data", "basis", "biplot", 
           "projection", "tour", "Geodesic interpolation",
           "Intrinsic data dimensionality", "Nonlinear model", "Local explanation"),
  Notation = c(
    "$n$", "$p$", "$X_{n \\times p}$", "$A_{p \\times d}$",
    "", "$Y_{n \\times d} = X_{n \\times p} \\cdot A_{p \\times d}$", 
    "", "", "$iid$", "", ""),
  Alias = c(
    "instance, item, row (of data)", "feature, column (of data)",
    "", "", "", "embedding", "", "", "", "black-box model", ""),
  Description = c(
    "A unit being measured across the variables.",
    "A measure taken across all observations.",
    "$n$ observations of $p$ variables, a complete quantitative matrix.",
    "Of linear projections, an othorgonal component mapping of $p$ down to $d$ dimensions.",
    "Visual representation of the basis, showing the direction and magnitude the variable contribute inscribed in a unit circle.", 
    "The resulting space the data multiplied by the basis.",
    "A dynamic linear projection animated over small changes to the projection basis.",
    "Creating intermediate basis frames along the shortest path of possible bases.",
    "The minimal dimensionality data can be represented with.",
    "A model with numerous or interactive terms that makes the term difficult to interpret.",
    "Approximation of the linear variable importance of a model in the vicinity of one observation.")
)

vimeo_link_df <- data.frame(
  Reference = c(
    "Figure \\@ref(fig:ch1fig3)", "Figure \\@ref(fig:ch2fig4)", 
    "Figure \\@ref(fig:casepenguins)", "Figure \\@ref(fig:casechocolates)", 
    "Figure \\@ref(fig:casechocolatesinverse)", "Figure \\@ref(fig:casefifa)", 
    "Figure \\@ref(fig:caseames)"),
  Description = c(
    "radial tour, penguins", "grand tour, penguins", "cheem,  penguins", 
    "cheem,  chocolates", "cheem,  chocolates (inverse)", "cheem, fifa", 
    "cheem, ames housing 2018"),
  Link = c("[vimeo.com/676723431](https://vimeo.com/676723431)",
           "[vimeo.com/676723441](https://vimeo.com/676723441)",
           "[vimeo.com/666431172](https://vimeo.com/666431172)",
           "[vimeo.com/666431143](https://vimeo.com/666431143)",
           "[vimeo.com/666431148](https://vimeo.com/666431148)",
           "[vimeo.com/666431163](https://vimeo.com/666431163)",
           "[vimeo.com/666431134](https://vimeo.com/666431134)")
)

supp_mats_df <- data.frame(
  Context = c(
    #"spinifex", 
    "spinifex", "spinifex", 
    #"cheem", 
    "cheem", "thesis", "thesis", "thesis"),
  Description = c(
    #"CRAN Link", 
    "vignette, Getting started with spinifex", 
    "vignette, Ggproto api", 
    #"CRAN Link", 
    "vignette, Getting started with cheem", 
    "repository", "thesis, pdf format", "thesis, html format"),
  Link = c(
    #"[CRAN.R-project.org/package=spinifex](https://CRAN.R-project.org/package=spinifex)",
    "[nspyrison.github.io/spinifex/articles/getting-started-with-spinifex.html](https://nspyrison.github.io/spinifex/articles/getting-started-with-spinifex.html)",
    "[nspyrison.github.io/spinifex/articles/ggproto-api.html](https://nspyrison.github.io/spinifex/articles/ggproto-api.html)",
    #"[CRAN.R-project.org/package=cheem](https://CRAN.R-project.org/package=cheem)",
    "[nspyrison.github.io/cheem/articles/getting-started-with-cheem.html](https://nspyrison.github.io/cheem/articles/getting-started-with-cheem.html)",
    "[github.com/nspyrison/thesis_ns](https://github.com/nspyrison/thesis_ns)",
    "[github.com/nspyrison/thesis_ns/blob/master/docs/thesis_ns.pdf](https://github.com/nspyrison/thesis_ns/blob/master/docs/thesis_ns.pdf)",
    "[https://nspyrison.github.io/thesis_ns/](https://nspyrison.github.io/thesis_ns/)")
)

## Set format and fonts for pdf vs html:
if(knitr::is_html_output()){
  fmt <- "html"
  fnt <- 12L
  esc <- FALSE ## HTML likes FALSE in vimeolinks
}else{
  fmt <- "latex"
  fnt <- 10L
  esc <- TRUE #FALSE ## latex needs \ escaping on urls to use false.
  #supp_mats_df$Link <- gsub("_", "\_", supp_mats_df$Link) 
}
```

## Glossary {#sec-glossary}

```{r glossary, fig.cap = "Use the caption arg in kable(), not this."}
kableExtra::kbl(
    glossary_df, format = fmt, align = rep("l", 4),
    booktabs = TRUE, longtable = TRUE, linesep = "", escape = esc,
    caption = "Glossary of terms") %>%
  kableExtra::kable_classic(font_size = fnt)
```


## Animated tour links

```{r vimeolinks, fig.cap = "Use the caption arg in kable(), not this."}
kableExtra::kbl(
    vimeo_link_df, format = fmt, align = rep("l", 3),
    booktabs = TRUE, longtable = TRUE, linesep = "", escape = esc,
    caption = "Animated tour links") %>%
  kableExtra::kable_classic(font_size = fnt)
```


## Supplementary material

```{r suppmats, fig.cap = "Use the caption arg in kable(), not this."}
kableExtra::kbl(
    supp_mats_df, format = fmt, align = rep("l", 3),
    booktabs = TRUE, longtable = TRUE, linesep = "", escape = esc,
    caption = "Supplementary material") %>%
  kableExtra::kable_classic(font_size = fnt)
```


<!--
### Tour taxonomy; path generation {#sec:path_generation}

A fundamental aspect of tours is the path of rotation. There are four primary distinctions of tour path generation [@buja_computational_2005]: random choice, data-driven, precomputed choice, and manual control.

* Random choice, *grand tour*, constrained random walks $p$-space. Paths are constrained for changes in direction small enough to maintain continuity and aid in user comprehension
    + torus-surface [@asimov_grand_1985]
    + at-random [@asimov_grand_1985]
    + random-walk [@asimov_grand_1985]
    + *local tour* [@wickham_tourr_2011], a sort of grand tour on a leash, such that it goes to a nearby random projection before returning to the original position and iterating to a new nearby projection.
* _guided tour_, optimizes an objective function/index of the projection using projection pursuit (PP) [@hurley_analyzing_1990], including the following implemented indexes:
    + holes [@cook_projection_1993] - moves points away from the center.
    + cmass [@cook_projection_1993] - moves points toward the center.
    + lda [@lee_projection_2005] - linear discriminant analysis, seeks a projection where 2 or more classes are most separated.
    + pda [@lee_projection_2010] - penalized discriminant analysis for use in highly correlated variables when classification is needed.
    + convex [@laa_using_2019] - the ratio of the area of convex and alpha hulls.
    + skinny [@laa_using_2019] - the ratio of the perimeter distance to the area of the alpha hull.
    + stringy [@laa_using_2019] - based on the minimum spanning tree (MST), the diameter of the MST over the length of the MST.
    + dcor2D [@grimm_mbgraphic:_2017; @laa_using_2019] - distance correlation that finds linear and nonlinear dependencies between variables.
    + splines2D [@grimm_mbgraphic:_2017; @laa_using_2019] - measure of nonlinear dependence by fitting spline models.
    + other user-defined objective indices can be applied to the framework provided in the *tourr* package @wickham_tourr_2011.
    + Another data-drive tour is the *dependence tour*, a combination of $n$ independent 1D tours. A vector describes the axis each variable will be displayed on. for example $c(1, 1, 2, 2)$ is a 4- to 2D tour with the first 2 variables on the first axis, and the remaining on the second.
        - *correlation tour* [@buja_data_1987], a special case of the dependence tour, analogous to canonical correlation analysis.
* Precomputed choice, *planned tour*, in which the path has already been generated or defined.
    + *little tour* [@mcdonald_interactive_1982], where every permutation of variables is stepped through in order, analogous to brute-force or exhaustive search.
    + a saved path of any other tour, typically an array of basis targets to interpolate between.
* Manual control, *manual tour*, a constrained rotation on selected manipulation variable and magnitude [@cook_manual_1997]. Typically used to explore the local area after identifying an interesting feature, perhaps via guided tour.
    + radial, fix angle of contribution, change magnitude radially.
    + oblique, along an oblique path of a dragged cursor


### Interpolation

NOTE: Search 'Interpolator' in Wickham’s tourr paper
After target bases are identified, the frames in-between need to be filled in. There are several methods to do so:

* Geodesic - via Gram-Schmidt process
* Givens rotations
* Householder reflections
.

### Tour software

Tours have yet to be widely adopted, due in part, to the fact that print and static pdf output does not accommodate dynamic viewing. Conceptual abstraction and technically density have also hampered user growth. Due to low levels of adoption and the rapid advancement of technology support and maintenance of such implementations give them a particularly short life span. Despite the small user base, there have been a fair number of tour implementations, including:
<!-- See Wickham’s thesis and C2 paper for partial lists. 

* spinifex [github.com/nspyrison/spinifex](https://github.com/nspyrison/spinifex) -- R package, all platforms.
* tourr [@wickham_tourr_2011] -- R package, all platforms.
* CyrstalVision [@wegman_visual_2003] -- for Windows.
* GGobi [@swayne_ggobi:_2003] -- for Linux and Windows.
* DAVIS [@huh_davis:_2002] -- Java based, with GUI.
* ORCA [@sutherland_orca:_2000] -- Extensible toolkit built in Java.
* VRGobi [@nelson_xgobi_1999] -- for use with the C2, tours in stereoscopic 3D displays.
* ExplorN [@carr_explorn:_1996] -- for SGI Unix.
* ExploRe [@hardle_xplore:_1995]
* XGobi [@swayne_xgobi:_1991] -- for Linux, Unix, and Windows (via emulation).
* XLispStat [@tierney_lisp-stat:_1990] -- for Unix and Windows.
* Explor4 [@carr_explor4:_1988] -- Four-dimensional data using stereo-ray glyphs.
* Prim-9 [@asimov_grand_1985;@fisherkeller_prim-9:_1974] -- on an internal operating system.
* liminal
* cheem
-->

