---
chapter: 1
knit: "bookdown::render_book"
---

# Research problem {-} 
<!-- {#ch:objectives} -->

Data and models are typically high-dimensional, with many variables or parameters. Developing new methods to visualize high dimensions have been a pursuit of statisticians, computer scientists and visualization researchers for decades. As technology evolves examining, extending, and assessing current techniques, in new environments, for new data challenges, is an important endeavor.  

This thesis focuses on tour methods for visualizing high-dimensional data. Tours are a family of algorithms for generating paths on the space of low-dimensional ($d=1, 2, 3, ..., p$) projections of high-dimensional ($p$) space. The resulting projection of the data (or model) is displayed using low-dimensional techniques such as histograms, dot plots, scatterplots, or parallel coordinate plots, and the path generates a movie or animation to shows many low-dimensional projections. The method can be applied with other techniques such as machine learning techniques like discriminant analysis, neural networks, support vector machines, to open the black box, and complements dimension reduction techniques like principal component analysis (PCA), multidimensional scaling (MDS) on nonlinear embeddings (e.g. tSNE). 


The primary research question is:

**Does allowing the user to steer the tour, facilitate the exploration and understanding of the sensitivity of structure to the original variables or parameters?** 

This question is reduced to four research objectives:

\begin{itemize}
  \item[RO \#A] \textbf{Can user controlled steering (UCS) be utilized in an environment providing non-dynamic animation?} (Chapter \ref{ch:spinifex}) This is previous experimental design that extend dynamic projection functionality currently available in the programming language R. It implements UCS steering and extends the animation paradigms that can be used for touring. These paradigms fall short of dynamic user interaction.
  \item[RO \#B] \textbf{What benefits does UCS provide over popular alternatives?} (Chapter \ref{ch:UCS_benefits}) Tentative planned future work of a case study comparing USC with commonly used static alternatives, such as principal component analysis (PCA), linear discriminant analysis (LDA), multi-dimensional scaling (MDS), and t-distributed nearest neighbor embeddings (tSNE).
  \item[RO \#C] \textbf{How do we extend UCS to 3D?} (Chapter \ref{ch:UCS_in3d}) This future experimental design will scaling UCS to 3 dimensions (novel contribution) and extend upon available functionally in the game engine Unity for compatible front ends across display devices. 
  \item[RO \#D] \textbf{Does UCS with 3D displays provide perception benefits over 2D displays?} (Chapter \ref{ch:UCS_3dvs2d}) This future empirical study explores the efficacy of bringing USC into 3D as compared across various display devices. 
\end{itemize}


## Methodology

As outlined above, RO #A & C uses *experimental design* in R and R & C# Unity respectively. RO #B is a *case study* comparison between UCS and alternatives. An *empirical research* explores the efficacy of UCS across display type in RO #D.




<!-- 
The big question:
1.) Does allowing the user to steer the tour facilitate exploration of the sensitivity of structure?
____
1a) Can the manual tour algorithm be implemented in an environment provided only animation technology?
-- for panel defense: why R; data science; people currently only looking at PCA and MDS, R and Python is the right place for it.
1b) what benefits to user-controlled steering (UCS) Provide over current practice? (comparative study)
Guided vs guided + manual, PCA/MDS vs manual, random projections vs manual. 
-- lit: current multivariate literature. examples of stopping at PCA, MDS, t-SNE?
1c) How can we extend the manual tour to 3D? (chap 5 HCI) (exploratory design)
--c2 was the manipulation space of 2D, not true $d=3$.
1d) Does 3D UCS provide benefits over UCS in 2D. (chap 4 Display Type -> chap6) (comparative study)
--for lit follow kim's chapter's refs
-->
