---
chapter: 3
knit: "bookdown::render_book"
---

# *spinifex*: extending *tourr* with manual tours and graphic display {#ch:spinifex}

## Abstract

$\theta$ $\lt$

Touring teqniques offer a great opertunity for data-space vizualization of ($p _gt 3$) multivariate data sets. This paper discusses the *R* package *spinifex*, which adds support for the manual tour, which is particularly usefuly for exploring the local structure after identifying a feature of interest, perhaps via guided tour. Additionally, *spinifex* extends graphic outputs to *plotly* and *gganimation*. This work extends the functionality of and is compatible with *tourr*.

Keywords: grand tour, projection pursuit, manual tour, tourr, touring, high dimenson visualization, hihg dim vis, dimensionality reduction, visualization, statistical graphics, data-space.


## Introduction

*

## Other content:

* Supply an orthonormal basis, **B**_{[p x d]}.
Let *d = 2* for illustration.
* Select a manip var, *k*, and use the Gram-Schmidt process to orthornormalize the concatenation of the zero vector with the *k*-th element set to 1, yielding the manipulation space, **M**_{[p x d+1]}.

\begin{align*}
  \textbf{M}_{[p,~d+1]}
    &= Orthnormalize_{GS}( \textbf{B}_{[p,~d]}|\textbf{e}_{k~[p,~1]} ) \\
    &= Orthnormalize_{GS}
    \left(
      \begin{bmatrix}
        B_{1,~1} & B_{1,~2}\\
        B_{2,~1} & B_{2,~2}\\
        \vdots   & \vdots  \\
        B_{k,~1} & B_{k,~2}\\
        \vdots   & \vdots  \\
        B_{p,~1} & B_{p,~2}
      \end{bmatrix}
    ~|~
      \begin{bmatrix}
      0 \\
      0 \\
      \vdots \\
      1 \\
      \vdots \\
      0
      \end{bmatrix}
    \right)
\end{align*}

* Select $\theta$, angle of rotation with-in the plane of the XY projection, and a vector of $\phi_i$, the angle of out-of plane rotation, orthagonal to the projection plane (relative to $\phi_1$, the transformation $\phi_i$ - $\phi_1$ proved to be helpful to discuss $\phi$ relative to the Z axis.)

**For $i$ in 1 to n_slide:**

* For each $\phi_i$, post multiplying 

**M**_{[p, d+1]} by a rotation matrix, **R**_{d+1, d+1} producing as many basis-projections, **P**_{b[p, d+1]}.

\begin{align}
  \textbf{P}_{b[p,~d+1]}
    &= \textbf{M}_{[p,~d+1]} ~*~ \textbf{R}_{[d+1,~d+1]}
    &= \begin{bmatrix}
        M_{1,~1} & M_{1,~2} & M_{1,~3} \\
        M_{2,~1} & M_{2,~2} & M_{2,~3} \\
        \vdots   & \vdots   & \vdots   \\
        M_{p,~1} & M_{p,~2} & M_{p,~3}
    \end{bmatrix}
      ~*~
    \begin{bmatrix}
      c_\theta^2 c_\phi s_\theta^2 &
      -c_\theta s_\theta (1 - c_\phi) &
      -c_\theta s_\phi \\
      -c_\theta s_\theta (1 - c_\phi) &
      s_\theta^2 c_\phi + c_\theta^2 &
      -s_\theta s_\phi \\
      c_\theta s_\phi &
      s_\theta s_\phi &
      c_\phi
    \end{bmatrix}
\end{align}


* To get back to data-space post multply each projection basis by the data, **X**_{[n x p]}, for **P**_{d[n x d+1]}.

\begin{align}
  \textbf{P}_{d[n,~d+1]}
    &= \textbf{X}_{[n,~p]} ~*~ \textbf{P}_{b[p,~d+1]}
    &= \begin{bmatrix}
      X_{1,~1} & \dots & X_{1,~p} \\
      X_{2,~1} & \dots & X_{2,~p} \\
      \vdots   & \vdots & \vdots  \\
      X_{n,~1} & \dots & X_{n,~p}
    \end{bmatrix}
      ~*~
    \begin{bmatrix}
      P_{b:1,~1} & P_{b:1,~2} & P_{b:1,~3} \\
      P_{b:2,~1} & P_{b:2,~2} & P_{b:2,~3} \\
      \vdots     & \vdots     & \vdots     \\
      P_{b:p,~1} & P_{b:p,~2} & P_{b:p,~3}
    \end{bmatrix}
\end{align}


* View the first two variables from each projection in sequence for an XY scatterplot. The remaining variable is sometimes utilized to produce depth cues used in conjunction with the XY scatterplot.

# ```{r}
# library(spinifex)
# flea_std <- tourr::rescale(tourr::flea[,1:6])
# rb <- tourr::basis_random(n = ncol(flea_std))
# 
# spinifex(data = flea_std, basis = rb, manip_var = 4)
# ```
#could not find function "render_slideshow"..