---
chapter: 3
knit: "bookdown::render_book"
---

```{r setup_03_chap, include=FALSE}
knitr::opts_chunk$set(
  fig.align = "center",
  echo = TRUE, 
  message = FALSE,
  warning = FALSE,
  error = FALSE,
  collapse = TRUE,
  comment = "",
  cache = FALSE, 
  cache.lazy = FALSE
)
```

# Work in progress {#ch:workinprogress}

Extending the algorithm for UCS in 2D for generalized use in graphics environments is fundamental to the extension of the UCS into 3D space. This forms the foundation for future work addressed in the remaining research objectives. This is a synthesis of the work that will be submitted to the R Journal. A wider discussion of implementation as an *R* package and application to high energy physics data [@wang_visualizing_2018; @cook_dynamical_2018] is attached in appendix \ref{ch:spinifex_paper} formatted as a paper.

## RO #1) How can UCS be generalized to work within graphic-specific environments for 2D projections?

This chapter builds off of *manual tours* [@cook_manual_1997] and modifies the algorithm for generalized use in graphics implementations. Manual tours allow users to rotate a selected variable into and out of a 2D projection of high-dimensional space for user-controlled steering (UCS). The primary use is to determine the sensitivity of the structure to the contributions of a selected manipulation variable. This is particularly powerful for exploring the local structure once a feature of interest has been identified, for example, by a guided tour. 


## Algorithm {#sec:algorithm}

The algorithm for generating a manual tour path involves these steps:

1. Given a 2D projection basis, choose a variable to explore. This is called the "manip" variable.
2. Create a 3D manipulation space, where the manip variable has a full contribution.
3. Generate a rotation sequence which zeros coefficient and increases it to 1 before returning to the initial position.

### Step 1 Choose variable of interest

Start with multivariate data in an $n \times p$ numeric matrix, and an orthonormal (orthogonal and each column normalized to have a norm of 1) $p \times d$ basis set is describing the projection from $p-$ to $d-$space. Select a manipulation (manip) variable. The coefficients of this variable will be operated on.


### Step 2 Create the manip space

Use the Gram-Schmidt process to orthonormalize another dimension on the basis with the full contribution on the manip variable. This brings the basis into a 3D manip space. The new dimension giving the basis room to rotate 'out-of-plane', akin to being able to lift a piece of paper, rather than being confined to the top of a table. 

### Step 3 Generate rotation

Define or capture a sequence of values for two angles, the 'in-plane' and 'out-of-plane', picture within an $XY$ plane, and out of $Z$-axis. For the corresponding value in each set, rotate (post multiply) the manip space according to a rotation matrix.


## Display projection sequence

Once the path has been generated, return to data-space matrix multiply the data with the rotated manip space. Plot the first two components as an $XY$-scatterplot for each frame. The projected data is commonly shown with reference axes, the coefficients of each variable extending from a unit circle showing the direction and magnitude of contribution to the 2D projection space.


