---
chapter: 4
knit: "bookdown::render_book"
---

# The effect of display type in perception of structure in high dimensional data {#ch:display_type}

Display types come in a plethora of sizes and technologies each is unique and optimized for specific uses and viewing conditions. It's a rapidly changing and shifting environment with a plethora of applications. Which and how to best use 2d computer minters will generate as many varied opinions as people asked. The question is only exaggerated when 3d display devices are considered.

The bulk of previous work embeds in 2-space, for display on traditional monitors. @nelson_xgobi_1998 performed a small ($n=15$) experimental study comparing tasks performed across 2d and 3d touring displays. The XGobi interface was used on a standard 2d monitor while VR-Gobi (on the C2 setup) was used VR display without head tracking. The accuracy 3 tasks: clustering, intrinsic data dimensionality and radial sparseness was recorded along with the speed of a data brushing task. Accuracy was the same for the dimensionality task, while the d3 display out performed 2d on clustering, and even more so on the radial sparsity. However, time taken to brush a cluster was less than half the time in 2d display as compared with 3d. 

I purpose another experimental study comparing touring across display dimension in 4 instances: standard 2d monitor, stereoscopic 3d monitor (on a zSpace 200), and head-mounted VR goggle (HTC Vive), and immersion in a CAVE environment. Implementation in the game engine Unity will allow for a standardized user interface. 3 tasks of structure perception will be conducted across 2 data sets of high energy physics data already in publication [@wang_visualizing_2018; @cook_dynamical_2018]. Task order will be randomly assigned to minimize learning bias. Participants will perform the 3 tasks, on each of the display devices, for each of the data sets. Time, and accuracy will be tracked, and participants will be asked to fill out a small survey with demographics data and subjective experience on a 5-point Likert scale.
