---
chapter: 5
knit: "bookdown::render_book"
---

# Human-computer interaction with displays of high dimensional data and functions {#ch:hci}

@wagner_filho_immersive_2018 performed an $n=30$ empirical study of PCA embedded projections, and perception error across 4 tasks and 3 display types: 2d, 3d, and immersive. Overall task error was less in 3d and immersive relative to 2d. According to user Likert-scale 2d is slightly easier to navigate and slightly more comfortable. On the flip-side 3d and immersive are slightly easier to interact and moderately easier to find information. 

Info visualization in virtual spaces has been through waves of popularity since the 80's, results seems to produce conflicting results, and are regularly conflated by mismatch in user familiarity between 2d and 3d displays as discussed in @marriott_immersive_2018 and others.

Immerse analytics, is becoming more and more popular. More research needing to be conducted to shed light onto previous mixed results. However, the results of  
@wagner_filho_immersive_2018, @nelson_xgobi_1998 and, @arms_benefits_1999 point positive light on 3d and immerse spaces improving perception of project high dim data. The Immerse Analytics group at Monash University have been programming packages in C#, for use with the Unity game engine for such uses (@cordeil_imaxes:_2017, @cordeil_immersive_2019). I will extend Cordeil's Immersive Analytics Toolkit (IATK) framework and implement dynamic communication with R scripts to apply 2d, 3d and touring in virtual spaces, and leave room to implement other dimensionality reduction methods in Unity.

