---
chapter: 7
knit: "bookdown::render_book"
---

# PhD timeline {-} 


```{r timeline, echo=F,}
#out.extra='angle=90
## working from: https://stats.andrewheiss.com/misc/gantt.html
library(tidyverse)
library(lubridate)
library(scales)

tasks <- tribble(
  ~Start,       ~End,         ~Project,     ~Task,
  "2018-04-01", "2019-06-01", "UCS in 2D",  "RO: A) spinifex package, 2D UCS",
  "2018-04-01", "2019-06-01", "UCS in 2D",  "spinifex code",
  "2018-12-01", "2019-03-01", "UCS in 2D",  "spinifex paper",
  "2019-03-01", "2019-06-01", "UCS in 2D",  "spinifex Submission (R Journal)",
  "2019-01-01", "2019-03-01", "Milestones", "Canidature confirmation",
  
  "2019-03-01", "2019-12-01", "UCS in 3D",  "RO: C) Tours, UCS in 3D",
  "2019-03-01", "2019-08-01", "UCS in 3D",  "UCS to IATK, C# code",
  "2019-06-01", "2019-09-01", "UCS in 3D",  "UCS in 3D paper",
  "2019-09-01", "2019-12-01", "UCS in 3D",  "UCS in 3D Submission (VAST)",
  "2020-01-01", "2020-03-01", "Milestones", "Mid canidature review",
  
  "2019-10-01", "2020-09-01", "UCS, 2D vs 3D", "RO: D) UCS across disp type, 2D vs 3D",
  "2019-10-01", "2020-02-01", "UCS, 2D vs 3D", "2D vs 3D C# code",
  "2020-01-01", "2020-04-01", "UCS, 2D vs 3D", "2D vs 3D Experimental survey",
  "2020-03-01", "2020-06-01", "UCS, 2D vs 3D", "2D vs 3D paper",
  "2020-06-01", "2020-09-01", "UCS, 2D vs 3D", "2D vs 3D Submission (CHI)",
  
  "2020-04-01", "2020-12-01", "UCS Benefits", "RO: B) UCS Benefits over alternatives",
  "2020-04-01", "2020-08-01", "UCS Benefits", "UCS Benefits C# code and comparison",
  "2020-06-01", "2020-09-01", "UCS Benefits", "UCS Benefits paper",
  "2020-09-01", "2020-12-01", "UCS Benefits", "UCS Benefits Submission (VAST)",
  
  "2020-11-01", "2021-03-01", "Milestones", "pre-submission presentation",
  "2021-01-01", "2021-04-01", "Milestones", "thesis completion and submission"
)

# Convert data to long for ggplot
tasks.long <- tasks %>%
  mutate(Start = ymd(Start),
         End = ymd(End)) %>%
  gather(date.type, task.date, -c(Project, Task)) %>%
  #arrange(date.type, task.date) %>%
  mutate(Task = factor(Task, levels=rev(unique(Task)), ordered=T))
# Custom theme for making a clean Gantt chart
theme_gantt <- function(base_size=11) {
  ret <- theme_bw(base_size) %+replace%
    theme(panel.background = element_rect(fill="#ffffff", colour=NA),
          axis.title.x=element_text(vjust=-0.2), axis.title.y=element_text(vjust=1.5),
          title=element_text(vjust=1.2),
          panel.border = element_blank(), axis.line=element_blank(),
          panel.grid.minor=element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_line(size=0.5, colour="grey80"),
          axis.ticks=element_blank(),
          legend.position="bottom", 
          axis.title=element_text(size=rel(0.8)),
          strip.text=element_text(size=rel(1)),
          strip.background=element_rect(fill="#ffffff", colour=NA),
          panel.spacing.y=unit(1.5, "lines"),
          legend.key = element_blank())
  
  ret
}

# Calculate where to put the dotted lines that show up every three entries
x.breaks <- seq(length(tasks$Task) + 0.5 - 3, 0, by=-3)

# Build plot
timeline <- ggplot(tasks.long, aes(x=Task, y=task.date, colour=Project)) + 
  geom_line(size=6) + 
  geom_vline(xintercept=x.breaks, colour="grey80", linetype="dotted") + 
  guides(colour=guide_legend(title=NULL)) +
  labs(x=NULL, y=NULL) + coord_flip() +
  scale_y_date(date_breaks="2 months", labels=date_format("%b ‘%y")) +
  theme_gantt() + theme(axis.text.x=element_text(angle=45, hjust=1)) +
  scale_color_brewer(palette = "Dark2")

timeline
```

Also submitted via online milestone form:

- FIT 5144 hours
    - >120 hours **Completed**
- WES Academic record
    - FIT6021: 2018 S2, **Completed** with Distinction
    - FIT5144: 2019 S1+2, **Upcoming**
    - FIT5113: 2018 S2, **Exemption submitted**
- myDevelopment - IT: Monash Doctoral Program - Compulsory Module
    - Monash Graduate Research Student Induction: **Completed** 
    - Research Integrity - Choose the Option most relevant: **Completed** (2 reqiured of 4)
    - Faculty Induction: **Content unavailable** ("currently being updated and will be visible in this section soon". Induction To be completed within 6 months of commencement)

# Acknowledgements {-} 

This thesis report is generated using R[@r_core_team_r:_2018], and Rmarkdown[@xie_r_2018], where code and explanation are kept together, following reproducible research practice. The code can be found at: https://github.com/nspyrison/Confirmation
