---
knit: "bookdown::render_book"
---

\appendix

# Glossary {#ch:glossary}

## Tour notation {#sec:tour_notation}

Tour notation varies across articles and authors. In my work, I use the following:

* $n$, number of observations in the data.
* $p$, number of numeric variables, the dimensionality of data space.
* $d$, the dimensionality of projection space.
* $\textbf{X}_{[n,~p]}$, a data matrix in variable-space, $\textbf{X} \in \mathbb{R}^{p}$. Typically centered, scaled, and optionally sphered.
* $\textbf{B}_{[p,~d]}$, orthonormal (orthogonal and each column normalized to a norm of 1) basis set, defining the axes directions for the projection from $p-$ to $d-$space.
* $\textbf{Y}_{[n,~d]}$, projected data matrix in projection-space, $\textbf{Y} \in \mathbb{R}^{d}$.
* Reference axes (or reference frame), a display showing how each variables coefficient(s) contribute to a projection. Either on its own axis (1D) or relative to a unit circle (2D).
* Geometric objects are referred to in generalized dimensions; the use of the term plane is not necessarily a 2D surface, but a hyperplane in the arbitrary dimensions of the projection space.


## Data visualization terminology {#sec:3d-terminology}

* 2D - representation of data in 2 dimensions, without the use of depth perception cues and minimal aesthetic mapping (such as color, size, and height) to data points.
* 2.5D - following the definition given in @ware_designing_2000: visualizations that are essentially 2D but select depth cues are used to provide some suggestion of 3D. However, the term 2.5D is commonly used for several meanings *due to the ambiguous use of 2.5D, this document errs on the side stating 3D with descriptions of depth cues used*.
* 3D - visualizations of 3 dimensions with liberal use of depth cues unless otherwise qualified.
* Depth perception cues - an indication that indicates the depth to an observer, including:
    * linear perspective - the property of parallel lines converging on a vanishing point.
    * aerial perspective - objects that far away have lower contrast and color saturation due to light scattering in the atmosphere.
    * occultation (or interposition) - where closer objects partially block the view of further objects.
    * motion perspective/parallax - closer objects, move across the field of view faster than further objects.
    * accommodation - the change of focal length due to change in the shape of the eye. Effective for distances of less than 2 meters.
    * binocular stereopsis/disparity - the use of 2 images of slightly varied angles from the horizontal distance of the eyes. The disparity for distant objects is small, but it is significant for nearby objects.
    * binocular convergence - The ocular-motor cue due to stereopsis focusing on the same objects. Convergence is effective for distances up to 10 meters.
* Virtual reality (VR) - an immersive experience of computer-generated sensory input.
* Augmented reality (AR) - view of physical spaces with augmenting/ supplementing sensory input of information.
* Mixed reality (MR) - a mix of physical and virtual realities with objects from both interacting in real time. This differs from AR by the flow of interaction; AR augments physical reality while MR has reciprocating interactions.
* Extended reality (XR) - any degree of virtual, augmented, or mixed reality.
* Scatterplot matrices (SPLOMs) - matrix display of pair-wise 2D scatterplots, sometimes with 1D density on the diagonal.
* Human-in-the-loop - any model that requires human interaction [@karwowski_international_2006].